INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_REDSHIRT');
INSERT IGNORE INTO roles(name) VALUES('ROLE_STARTER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_MVP');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');